### ISSUE TITLE
No living connection

### ISSUE THREAD

**Issue by imran-baig-se** [infuse89/pm2-elasticlogs#2]
``tail -f /Users/imranbaig/.pm2/logs/pm2-elasticlogs-error.log
  No living connections

{ Error: No Living connections
    at sendReqWithConnection (/Users/imranbaig/.pm2/modules/pm2-elasticlogs/node_modules/elasticsearch/src/lib/transport.js:207:15)
    at next (/Users/imranbaig/.pm2/modules/pm2-elasticlogs/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  message: 'No Living connections',
  body: undefined,
  status: undefined }``

I do have docker containers running for ELK.

** pm2 show pm2-elasticlogs
 Describing process with id 0 - name pm2-elasticlogs
┌───────────────────┬───────────────────────────────────────────────────────────────────────────────────┐
│ status            │ online                                                                            │
│ name              │ pm2-elasticlogs                                                                   │
│ restarts          │ 0                                                                                 │
│ uptime            │ 11m                                                                               │
│ script path       │ /Users/imranbaig/.pm2/modules/pm2-elasticlogs/node_modules/pm2-elasticlogs/app.js │
│ script args       │ N/A                                                                               │
│ error log path    │ /Users/imranbaig/.pm2/logs/pm2-elasticlogs-error.log                              │
│ out log path      │ /Users/imranbaig/.pm2/logs/pm2-elasticlogs-out.log                                │
│ pid path          │ /Users/imranbaig/.pm2/pids/pm2-elasticlogs-0.pid                                  │
│ interpreter       │ node                                                                              │
│ interpreter args  │ N/A                                                                               │
│ script id         │ 0                                                                                 │
│ exec cwd          │ /Users/imranbaig/.pm2/modules/pm2-elasticlogs/node_modules/pm2-elasticlogs        │
│ exec mode         │ fork_mode                                                                         │
│ node.js version   │ 9.2.0                                                                             │
│ watch & reload    │ ✘                                                                                 │
│ unstable restarts │ 0                                                                                 │
│ created at        │ 2018-04-02T06:59:55.935Z                                                          │
└───────────────────┴───────────────────────────────────────────────────────────────────────────────────┘
Process configuration
┌─────────────────────┬──────────────────────┐
│ app_name            │ all                  │
│ elasticsearch_index │ logs                 │
│ elasticsearch_host  │ http://es-local:9200 │
└─────────────────────┴──────────────────────┘
 Code metrics value
┌─────────────────┬────────┐
│ Loop delay      │ 3.28ms │
│ Active requests │ 0      │
│ Active handles  │ 4      │**

**Comment by imran-baig-se** [comment]
@infuse89 please advise
